{{- if and .Values.gc.enabled .Values.gc.config.reconciler.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "batch-gateway.gc.fullname" . }}-pod-watcher
  labels:
    {{- include "batch-gateway.gc.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
{{- end }}
